ALTER TABLE user
    MODIFY COLUMN username VARCHAR(16) NOT NULL UNIQUE;
ALTER TABLE post
    MODIFY COLUMN image BLOB NOT NULL UNIQUE,
    MODIFY COLUMN caption BLOB NOT NULL DEFAULT '';
ALTER TABLE comment
    MODIFY COLUMN detail BLOB NOT NUll;